name: campus_hub
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  # ──────────── UI ────────────
  cupertino_icons: ^1.0.8

  # ──────────── State Management ────────────
  flutter_bloc: ^9.1.1
  equatable: ^2.0.8

  # ──────────── Dependency Injection ────────────
  get_it: ^9.2.0

  # ──────────── Network ────────────
  dio: ^5.9.1

  # ──────────── Local Storage ────────────
  shared_preferences: ^2.5.4

  # ──────────── Form ────────────
  flutter_form_builder: ^10.3.0+2
  form_builder_validators: ^11.3.0

  # ──────────── Firebase ────────────
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  cloud_firestore: ^6.1.2
  firebase_storage: ^13.0.6

  # ──────────── Media ────────────
  image_picker: ^1.2.1

  # ──────────── Core Utils ────────────
  wonzy_core_utils: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # ──────────── Linting ────────────
  flutter_lints: ^6.0.0

  # ──────────── Code Generation ────────────
  flutter_launcher_icons: ^0.14.2
  flutter_native_splash: ^2.4.4
  build_runner: ^2.11.1


# --- APP ICON CONFIG ---
flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/app_logo/campushub_icon.png
  remove_alpha_ios: true
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: assets/app_logo/campushub_icon.png

# --- SPLASH CONFIG ---
flutter_native_splash:
  color: "#FFFFFF"
  image: assets/app_logo/campushub_icon.png
  android: true
  ios: true
  android_12:
    color: "#FFFFFF"
    image: assets/app_logo/campushub_icon.png

flutter:
  uses-material-design: true

  assets:
    - assets/app_logo/campushub_icon.png
    - assets/profil/